name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation (pink)
        uses: Platane/snk@v3
        with:
          github_user_name: SouzaSther
          outputs: |
            dist/github-contribution-grid-snake-pink.svg?color_snake=ff69b4&color_dots=ffe4ec,ffc0cb,ffb6c1,ff69b4,db7093

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
